name: docker
on:
  push:
    branches:
      - 'main'
      - 'r/docker'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set short git commit SHA
        id: vars
        run: |
          ss=$(echo ${{ github.sha }} | cut -c1-4)
          echo "$ss"
          echo "SS=$ss" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./cmd/shovel/Dockerfile
          push: true
          tags: indexsupply/shovel:latest,indexsupply/shovel:${{ env.SS }}
